spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/itmo_market  # ← localhost → postgres
    username: itmo_user  # ← postgres → itmo_user
    password: itmo_password  # ← postgres → itmo_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        default_schema: user_service
    show-sql: false
  
  flyway:
    locations: classpath:db/migration
    schemas: user_service


server:
  port: 8081
  servlet:
    context-path: /api/v1


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # ← localhost → eureka-server


logging:
  level:
    root: INFO
    ru.itmo.market: DEBUG
